// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt6fSvAwT337VOpiy7DCI1aHGhbrCLjhM',
    appId: '1:1096775021335:web:28320ecf4a746d38243d52',
    messagingSenderId: '1096775021335',
    projectId: 'encrypted-chat-app-16c5f',
    authDomain: 'encrypted-chat-app-16c5f.firebaseapp.com',
    storageBucket: 'encrypted-chat-app-16c5f.firebasestorage.app',
    measurementId: 'G-SHS7F08M8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuxqWm_VJjHbIsvm2kWQdD26L_hGXNFJw',
    appId: '1:1096775021335:android:941be56af226bbe1243d52',
    messagingSenderId: '1096775021335',
    projectId: 'encrypted-chat-app-16c5f',
    storageBucket: 'encrypted-chat-app-16c5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiFU_9MFhGvgQvBdebCqlW_xKylzYzqBg',
    appId: '1:1096775021335:ios:b7838f48785960b7243d52',
    messagingSenderId: '1096775021335',
    projectId: 'encrypted-chat-app-16c5f',
    storageBucket: 'encrypted-chat-app-16c5f.firebasestorage.app',
    iosBundleId: 'com.example.encryptedChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiFU_9MFhGvgQvBdebCqlW_xKylzYzqBg',
    appId: '1:1096775021335:ios:b7838f48785960b7243d52',
    messagingSenderId: '1096775021335',
    projectId: 'encrypted-chat-app-16c5f',
    storageBucket: 'encrypted-chat-app-16c5f.firebasestorage.app',
    iosBundleId: 'com.example.encryptedChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt6fSvAwT337VOpiy7DCI1aHGhbrCLjhM',
    appId: '1:1096775021335:web:79656e9c21a7f6c1243d52',
    messagingSenderId: '1096775021335',
    projectId: 'encrypted-chat-app-16c5f',
    authDomain: 'encrypted-chat-app-16c5f.firebaseapp.com',
    storageBucket: 'encrypted-chat-app-16c5f.firebasestorage.app',
    measurementId: 'G-N12RDTZGBM',
  );
}
